//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FioBankApiClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FioBankApiClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token can not be empty..
        /// </summary>
        internal static string AccessTokenCanNotBeEmpty {
            get {
                return ResourceManager.GetString("AccessTokenCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token contains forbidden characters:.
        /// </summary>
        internal static string AccessTokenHasForbiddenChars {
            get {
                return ResourceManager.GetString("AccessTokenHasForbiddenChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal length of access token is 64 characters..
        /// </summary>
        internal static string AccessTokenMinimalLength {
            get {
                return ResourceManager.GetString("AccessTokenMinimalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time cannot be earlier than DateTimeOffset.MinValue..
        /// </summary>
        internal static string DateTimeCannotBeEarlier {
            get {
                return ResourceManager.GetString("DateTimeCannotBeEarlier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ExceptionName} throws when calling the API. Request uri: &apos;{Uri}&apos;..
        /// </summary>
        internal static string ExceptionDuringFioApiCall {
            get {
                return ResourceManager.GetString("ExceptionDuringFioApiCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ExceptionName} throws when calling TryDeserializeAsync method..
        /// </summary>
        internal static string ExceptionDuringJsonDeserialization {
            get {
                return ResourceManager.GetString("ExceptionDuringJsonDeserialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter fioRequest can not be null..
        /// </summary>
        internal static string FioRequestNull {
            get {
                return ResourceManager.GetString("FioRequestNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status code: &apos;{StatusCode}&apos;. Server response: {ServerResponse} Request uri: &apos;{Uri}&apos;. {Resource}.
        /// </summary>
        internal static string HttpStatusCodeValue {
            get {
                return ResourceManager.GetString("HttpStatusCodeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON deserialization result is null..
        /// </summary>
        internal static string JsonDeserializationResultNull {
            get {
                return ResourceManager.GetString("JsonDeserializationResultNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MovementId must be a positive value..
        /// </summary>
        internal static string MovementIdMustBePositive {
            get {
                return ResourceManager.GetString("MovementIdMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger is null (Console), using NullLogger..
        /// </summary>
        internal static string NullLoggerConsole {
            get {
                return ResourceManager.GetString("NullLoggerConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger is null (Debug),using NullLogger..
        /// </summary>
        internal static string NullLoggerDebug {
            get {
                return ResourceManager.GetString("NullLoggerDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger is null (Trace), using NullLogger..
        /// </summary>
        internal static string NullLoggerTrace {
            get {
                return ResourceManager.GetString("NullLoggerTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream can not be closed. Method:TryDeserializeAsync Parameter: streamContent..
        /// </summary>
        internal static string ResponseStreamClosed {
            get {
                return ResourceManager.GetString("ResponseStreamClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream can not be null. Method:TryDeserializeAsync Parameter: streamContent..
        /// </summary>
        internal static string ResponseStreamNull {
            get {
                return ResourceManager.GetString("ResponseStreamNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement ID must be a positive value..
        /// </summary>
        internal static string StatementIDMustBePositive {
            get {
                return ResourceManager.GetString("StatementIDMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum interval of 30 seconds between downloading data from the bank / uploading data to the bank is not observed of a specific token (regardless of format type). A specific token can only be used once for reading or writing within 30 seconds..
        /// </summary>
        internal static string StatusCodeConflict {
            get {
                return ResourceManager.GetString("StatusCodeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusCode InternalServerError with server response..
        /// </summary>
        internal static string StatusCodeInternalServerErrorWithContent {
            get {
                return ResourceManager.GetString("StatusCodeInternalServerErrorWithContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error indicates a non-existent, invalid or inactive token. Check the validity and correctness of the token in the Internet banking..
        /// </summary>
        internal static string StatusCodeInternalServerErrorWithoutContent {
            get {
                return ResourceManager.GetString("StatusCodeInternalServerErrorWithoutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A poorly sent query that the server cannot properly respond to. Check the URL parameters nin query/import..
        /// </summary>
        internal static string StatusCodeNotFound {
            get {
                return ResourceManager.GetString("StatusCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are downloading a large set of data. The download limit is set to a maximum of 50,000 moves. Adequately adjust the date range in the sent query, or you need to set a breakpoint for a more recent movement..
        /// </summary>
        internal static string StatusCodeRequestEntityTooLarge {
            get {
                return ResourceManager.GetString("StatusCodeRequestEntityTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data older than 90 days is requested without having been strongly authorized to access historical data..
        /// </summary>
        internal static string StatusCodeUnprocessableEntity {
            get {
                return ResourceManager.GetString("StatusCodeUnprocessableEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year must be a positive value..
        /// </summary>
        internal static string YearMustBePositive {
            get {
                return ResourceManager.GetString("YearMustBePositive", resourceCulture);
            }
        }
    }
}
